### ISSUE TITLE
Error in README.md

### ISSUE THREAD

**Issue by flaschetelefon** [Snagnar/arduino-generic-data-logger#1]
You claim that your Sketch works reliably at an altitude > 30,000 m. But isn't it the hardware's responsibility that it works at such an altitude? Furthermore, I know from various sources that it is not confirmed that your balloon has reached the 30,000 m at all. Also, I doubt that the electronics had a temperature of -20 degrees Celsius at that altitude. And I assume that you have protected the electronics from such influences. 

I request you to correct these errors in the README.md!!

**Comment by Snagnar** [comment]
No.
